filepath: ""
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
releases:
- chart: dev/golang-gk
  version: 0.0.1
  name: golang-gk
  forceNamespace: ""
  skipDeps: null
templates: {}
missingFileHandler: ""
renderedvalues: {}
