apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        gokula-krishna-dev/go-jks-test: true
        gokula-krishna-dev/go-jkx-test: true
        gokula-krishna-dev/golang-gk: true
        gokula-krishna-dev/golang-jx: true
        gokula-krishna-dev/jx3-minikube: true
        gokula-krishna-dev/new-go-lang: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        gokula-krishna-dev/go-jks-test: merge
        gokula-krishna-dev/go-jkx-test: merge
        gokula-krishna-dev/golang-gk: merge
        gokula-krishna-dev/golang-jx: merge
        gokula-krishna-dev/jx3-minikube: merge
        gokula-krishna-dev/new-go-lang: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - gokula-krishna-dev/jx3-minikube
        - gokula-krishna-dev/go-jks-test
        - gokula-krishna-dev/go-jkx-test
        - gokula-krishna-dev/golang-gk
        - gokula-krishna-dev/golang-jx
        - gokula-krishna-dev/new-go-lang
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - gokula-krishna-dev/jx3-minikube
        - gokula-krishna-dev/go-jks-test
        - gokula-krishna-dev/go-jkx-test
        - gokula-krishna-dev/golang-gk
        - gokula-krishna-dev/golang-jx
        - gokula-krishna-dev/new-go-lang
      target_url: http://dashboard-jx.192.168.99.114.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
