# Source: golang-gk/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-16T10:18:16Z"
  deletionTimestamp: null
  name: 'golang-gk-0.0.3'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.3
      sha: 26957d5ec29d8d77e6a5a7882fff851d20348f99
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 9b3bffbebe13f19d5a7a66ccbfbcd995718ab59e
    - author:
        email: krishnagokula5e@gmail.com
        name: Gokula Krishna
      branch: master
      committer:
        email: krishnagokula5e@gmail.com
        name: Gokula Krishna
      message: |
        update
      sha: 63912a0274c2ef7cc735356e6764802755a3a74a
  gitHttpUrl: https://github.com/gokula-krishna-dev/golang-gk
  gitOwner: gokula-krishna-dev
  gitRepository: golang-gk
  name: 'golang-gk'
  releaseNotesURL: https://github.com/gokula-krishna-dev/golang-gk/releases/tag/v0.0.3
  version: v0.0.3
status: {}
